import globals from "globals";

// Имена, объявленные в одном файле js/ и используемые в других.
// Скрипты подключаются обычными <script> без модулей, поэтому всё
// живёт в одной глобальной области — для ESLint это надо перечислить
// явно, иначе no-undef ругался бы на каждое обращение.
// Список сгенерирован из объявлений верхнего уровня в js/*.js.
const sharedBrowserGlobals = [
  "accentVariants",
  "activeStatusBuckets",
  "activeTierCollections",
  "ANILIST_LIST_QUERY",
  "ANILIST_STATUS_MAP",
  "anilistDate",
  "anilistType",
  "animateCounters",
  "animateStackedBars",
  "applyNavLabels",
  "applyRvFilters",
  "applyTabPreferences",
  "applyTheme",
  "AUTOSYNC_CONFLICTS_KEY",
  "backupToastGlobal",
  "bindAnilistUser",
  "bindImport",
  "bindImportKeys",
  "bindPassports",
  "bindRvFilters",
  "buildMyPassport",
  "BUILTIN_CAT_KEYS",
  "BUILTIN_TAG_NAMES",
  "cache",
  "CAT_COLORS",
  "CAT_LABELS",
  "checkGithubUser",
  "checkTmdbKey",
  "cleanDate",
  "clearSyncConfig",
  "closeAddFromPassportModal",
  "closeCollectionModal",
  "closeCollectionModalOnOverlay",
  "closeReviewModal",
  "COLLAPSE_KEY",
  "confirmDialog",
  "confirmLeaveIfDirty",
  "collectionFileFor",
  "compareOneSidedHtml",
  "comparePairsHtml",
  "compareResultHtml",
  "compareSectionHtml",
  "coverFallbackAttrs",
  "createRepo",
  "disableAnimations",
  "waitForImages",
  "withTimeout",
  "createStatusFromImport",
  "csvToObjects",
  "currentSiteSettings",
  "DEFAULT_ACCENT",
  "DEFAULT_LABELS",
  "DEFAULT_STATUS_BUCKETS",
  "defaultScoreMap",
  "defaultStatusMap",
  "detectCsvFormat",
  "DISAGREE_THRESHOLD",
  "dateLocale",
  "domReady",
  "esc",
  "exportMyPassport",
  "extractIdsFromCover",
  "eyeButton",
  "eyeIcon",
  "cameraButton",
  "cameraIcon",
  "favPersonCard",
  "favTitleCard",
  "fetchAnilistMeta",
  "fetchAnilistUserList",
  "fetchReviews",
  "fetchSiteSettings",
  "fetchTmdbMeta",
  "findReviewForTitle",
  "fmtDateStr",
  "getCollapsed",
  "getSyncConfig",
  "getSyncState",
  "GRADE_ORDER",
  "gradeInlineHtml",
  "gradeLabels",
  "GRADES",
  "GRADES_DEF",
  "gradeScore",
  "gradeToShelf",
  "guessRussianPlural",
  "GUEST_KEY",
  "guestPassport",
  "guestViewHtml",
  "hexToRgb",
  "hslToHex",
  "ID_MATCH_ORDER",
  "i18nFill",
  "i18nGuessPlural",
  "i18nLang",
  "i18nPlural",
  "i18nRegister",
  "I18N_CURRENT",
  "I18N_EN",
  "I18N_LANGS",
  "applyI18n",
  "keyboardShortcutsHtml",
  "makeResizablePanel",
  "onAddFromPassportModalKey",
  "repoExists",
  "resolveConflict",
  "runSync",
  "saveSyncConfig",
  "setAppLanguage",
  "i18n",
  "imagePlaceholder",
  "imgFallbackAttrs",
  "IMPORT_ANILIST_ENDPOINT",
  "IMPORT_BATCH",
  "IMPORT_SOURCES",
  "IMPORT_STATUS_KEYS",
  "IMPORT_TMDB_BATCH",
  "IMPORT_TMDB_ENDPOINT",
  "IMPORT_TMDB_IMAGES",
  "importBusy",
  "importData",
  "importDoneHtml",
  "importFileHtml",
  "importKeysHtml",
  "importKeysOpen",
  "importMapHtml",
  "importMatchKeys",
  "importScoreMap",
  "importSkipExisting",
  "importSourcesHtml",
  "importStatusMap",
  "importStep",
  "importStyles",
  "impStat",
  "indexByKeys",
  "initBackupHistoryPanel",
  "isAdmin",
  "isAppContext",
  "isFavSectionVisible",
  "isHex",
  "isStatVisible",
  "isTierModeVisible",
  "leaveRoute",
  "loadCharGames",
  "loadFavorites",
  "loadHtml2Canvas",
  "loadImport",
  "loading",
  "loadNow",
  "loadPassports",
  "loadReviews",
  "loadStats",
  "loadTierlist",
  "makeGradeInfo",
  "makeSection",
  "MAL_TYPE_MAP",
  "manualCard",
  "matchKeys",
  "mergeIds",
  "mergeLabels",
  "MODE_KEY",
  "myGradedItems",
  "myGradeInfo",
  "NEW_STATUS_VALUE",
  "normalizeMalStatus",
  "normTitle",
  "onStatusBucketsChanged",
  "openCollectionModal",
  "openLibraryCover",
  "openReviewModal",
  "PALETTE_TOKENS",
  "parseAnilistLists",
  "parseCsv",
  "parseGoodreads",
  "parseImportFile",
  "parseLetterboxd",
  "parseMalXml",
  "parsePassport",
  "PASSPORT_FORMAT",
  "PASSPORT_VERSION",
  "passportIntroHtml",
  "passportMode",
  "passportsBusy",
  "passportStyles",
  "patchSiteSettings",
  "PH_SQ",
  "PH_TALL",
  "plural",
  "promptDialog",
  "pluralLabel",
  "ppChip",
  "ppMeta",
  "ppPoster",
  "ppSection",
  "ppStat",
  "proxyImagesToDataUrls",
  "rebuildGradesFromScale",
  "refreshOpenReviewsTab",
  "registerRoute",
  "renderAllTimeStats",
  "renderCounters",
  "renderDonut",
  "renderFavorites",
  "renderGradeChart",
  "renderImport",
  "renderNow",
  "renderPassports",
  "renderReviews",
  "renderRewatchStats",
  "renderRvFilterGroup",
  "renderStackedBarChart",
  "renderTagCloud",
  "renderTitleOfYear",
  "renderYearDigest",
  "resolveAccent",
  "reviewCard",
  "reviewModalBodyHtml",
  "rgbToHsl",
  "runImport",
  "rvBindCardClicks",
  "rvLastFiltered",
  "rvState",
  "saveCollapsed",
  "saveSettings",
  "saveTmdbKey",
  "scoresInFile",
  "setLeaveGuard",
  "siteLabel",
  "slugify",
  "sortByOrder",
  "SOURCE_FILTER_ORDER",
  "SOURCE_LABELS",
  "sourceBtnHtml",
  "splitImportItems",
  "startMapping",
  "statsBindAll",
  "statsCompletedYear",
  "statsRender",
  "statsState",
  "statsTopTitlesOfYear",
  "statsYearFiltersHtml",
  "submitNewCollection",
  "SUBTYPE_LABELS",
  "syncHideTagsToggle",
  "syncInFlight",
  "tabSwitchBindingsHtml",
  "TAG_CAT_CLASS",
  "tagHtml",
  "TAGS_MAP",
  "THEME_PRESETS",
  "themeOptions",
  "themePalette",
  "TIER_ROWS",
  "TL_TYPE_ORDER",
  "tlBindAll",
  "tlBindTooltip",
  "tlCharHeight",
  "tlCharsHtml",
  "tlExport",
  "tlFiltersHtml",
  "tlInferType",
  "tlModeToggleHtml",
  "tlMoveTip",
  "tlPresentTypes",
  "tlRender",
  "tlShowTip",
  "tlSlugify",
  "tlState",
  "tlTitlesHtml",
  "tlTooltipHtml",
  "tlTypeLabel",
  "tlYearFiltersHtml",
  "TMDB_KEY_STORAGE",
  "tmdbCacheKey",
  "tmdbKey",
  "tmdbPoster",
  "toggleSection",
  "MEDIA_TYPES",
  "TYPE_COLORS",
  "TYPE_FILTER_ORDER",
  "TYPE_LABELS",
  "TYPE_PLURAL",
  "unitForms",
  "updateFileBtnName",
  "updateSectionListHeadings",
  "visibleTierCollections",
  // грузится по требованию из app/js/vendor (см. loadHtml2Canvas)
  "html2canvas",

  // settings-edit.js разбит на settings-appearance.js/settings-stats.js/
  // settings-grades.js/settings-tabs.js/settings-app.js/settings-sync.js/
  // settings-shortcuts.js/settings-labels.js (и сам settings-edit.js как
  // каркас) — все они делят одну область видимости, как и раньше одним
  // файлом, поэтому их обращения друг к другу тоже нужно перечислить.
  "allCatLabels",
  "appInfo",
  "applyTextScale",
  "archiveLabel",
  "bindTabsDnd",
  "BUILTIN_CAT_DEFAULTS",
  "BUILTIN_COLLECTION",
  "BUILTIN_SUBTYPE_DEFAULTS",
  "BUILTIN_TYPE_DEFAULTS",
  "catColors",
  "collapsibleizeSettingsSections",
  "customCatKeys",
  "customSubtypeKeys",
  "customTags",
  "customTypeKeys",
  "detectApp",
  "favCollections",
  "favSectionLabels",
  "favSectionOrderState",
  "FAV_SECTIONS",
  "flashStatus",
  "hiddenFavSectionsState",
  "hiddenStatsState",
  "hiddenStatusesState",
  "hiddenSubtypes",
  "hiddenTabsState",
  "hiddenTierModesState",
  "hiddenTypes",
  "hideTagsAllOn",
  "loadAppPanel",
  "loadCurrentSettings",
  "openThemeGroup",
  "previewPalette",
  "rawSettings",
  "removedBuiltinCollection",
  "removedFavSections",
  "renderCollectionsList",
  "renderFavCollectionsList",
  "renderFavSectionsList",
  "renderLabelsPanel",
  "renderPalette",
  "renderScaleTypeGrid",
  "renderStatsList",
  "renderStatusesList",
  "renderSyncPanel",
  "renderTabsList",
  "renderThemeGrid",
  "renderTierModesList",
  "renderTypeColorsList",
  "renderVaultsPanel",
  "scaleType",
  "selectedTheme",
  "sePrevSkin",
  "settingsDirty",
  "shelves",
  "statusBuckets",
  "statusOrderState",
  "statusOrderedKeys",
  "subtypeLabels",
  "tabDragSrc",
  "tabLabels",
  "tabOrderState",
  "TAB_DEFS",
  "TAB_DEFS_BY_ID",
  "textScale",
  "themeColors",
  "tierCollections",
  "tierModeOrderState",
  "tierModeOrderedKeys",
  "tierTitlesLabel",
  "toggleCollectionEdit",
  "toggleFavCollectionEdit",
  "toggleFavSecEdit",
  "toggleStatusEdit",
  "toggleTabEdit",
  "toggleTierModeEdit",
  "typeColors",
  "typeLabels",
  "typePlural",
  "updateScaleBlocks",
];

const commonRules = {
  "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
  "no-undef": "error",
  eqeqeq: ["warn", "smart"],
  "no-var": "error",
  "prefer-const": "warn",
  // Пустой catch здесь — осознанный приём («нет файла — работаем на
  // значениях по умолчанию»), он встречается по коду и в комментариях
  // объяснён, ругаться на него не нужно.
  "no-empty": ["error", { allowEmptyCatch: true }],
};

export default [
  {
    // Чужая минифицированная библиотека (html2canvas-pro) лежит в
    // составе приложения, чтобы экспорт в картинку работал без
    // интернета. Линтовать её незачем и нечем: одна строка на 222 КБ
    // даёт сотни бессмысленных замечаний и прячет настоящие. Рядом по
    // той же причине собранный мобильный мост (его исходник — в
    // mobile/src, он и проверяется) и проект Android, где кода на
    // JavaScript нет вовсе.
    ignores: ["app/js/vendor/**", "app/js/mobile.bundle.js", "android/**"],
  },
  {
    // Фронтенд: обычные <script>, общая глобальная область
    files: ["app/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...Object.fromEntries(sharedBrowserGlobals.map((name) => [name, "writable"])),
      },
    },
    rules: {
      ...commonRules,
      // vars: "local" — не ругаться на функции верхнего уровня, которые
      // «нигде не используются». Половина из них вызывается из onclick=
      // в HTML, куда ESLint не заглядывает, так что иначе линтер выдавал
      // бы два десятка ложных предупреждений и его перестали бы читать.
      // Внутри функций неиспользуемые переменные по-прежнему ловятся.
      "no-unused-vars": ["warn", { vars: "local", args: "after-used", argsIgnorePattern: "^_" }],
    },
  },
  {
    // settings-edit.js разбит на несколько файлов (см. sharedBrowserGlobals
    // выше) — часть состояния объявлена `let` в одном файле, а
    // переприсваивается в другом, куда переехала соответствующая секция.
    // prefer-const этого не видит (файлы для него независимы) и в каждом
    // таком месте предлагает `const`, что сломало бы переприсваивание из
    // соседнего файла. В едином файле до разбиения этого предупреждения не
    // было — оно ложное, а не забытый рефакторинг.
    files: ["app/js/routes/settings-*.js"],
    rules: { "prefer-const": "off" },
  },
  {
    // Приложение: Electron, общий слой и вспомогательные скрипты —
    // обычный Node. core/ попал сюда же: там нет ничего от Node, но и
    // от браузера тоже, а правила одни и те же.
    files: ["electron/**/*.js", "core/**/*.js", "scripts/**/*.{js,mjs}", "tests/**/*.{js,mjs}"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.node },
    },
    rules: commonRules,
  },
  {
    // Проверки в браузере: сам файл — обычный Node, но куски внутри
    // page.evaluate выполняются на странице, и document с window там
    // настоящие. Разделять их по файлам ради линтера не стоит — тест
    // читается целиком.
    // Сюда же скрипт иконок: он тоже рисует в браузере.
    files: ["tests/browser/**", "tests/fixtures/**", "scripts/android-icons.mjs"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.node, ...globals.browser },
    },
    rules: commonRules,
  },
  {
    // Мобильный мост: собирается для браузера телефона, но пишется
    // модулями — их складывает esbuild.
    files: ["mobile/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.browser },
    },
    rules: commonRules,
  },
];
